# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: bb7a41d1-md-taco
  namespace: bb7a41d1
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
