# Source: cluster-api-byoh/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: bb7a41d1
  namespace: bb7a41d1
spec:
  clusterNetwork:
    pods:
      cidrBlocks: [10.233.64.0/18]
    serviceDomain: cluster.local
    services:
      cidrBlocks: [10.233.0.0/18]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: bb7a41d1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ByoCluster
    name: bb7a41d1
